### ISSUE TITLE
Register form extends past footer

### ISSUE THREAD

**Issue by sarahannnicholson** [sarahannnicholson/RBKWebsite#6]
Go to http://127.0.0.1:8000/register/
Notice the form overlaps on top of the footer

Solution 1
- Modify the DOM so the page scrolls (footer after the register form)

Solution 2
- Make the register form 2 columns

**Comment by JSZYN** [comment]
Fixed with https://github.com/sarahannnicholson/RBKWebsite/commit/d90703ec721ffca1393c5b16a63a409e72b2787f
